
      PARAMETER (RWEST  = -10.0, REAST  = 42.0)
      PARAMETER (RSOUT  = 26.0, RNORT  = 50.0)
      PARAMETER (DELTAL = 1./20.)
      PARAMETER (DELTAF = 1./20.)
      PARAMETER (NXP=(REAST-RWEST)/DELTAL+1)
      PARAMETER (NYP=(RNORT-RSOUT)/DELTAF+1)

